name: 'Group paths by glob pattern of directories'
description: 'Group paths by glob pattern of directories'
author: 'tapih'

branding:
  icon: 'heart'
  color: 'red'

inputs:
  paths:
    description: 'The list of paths to group in JSON'
    required: true
  glob:
    description: 'The glob pattern for grouping the directories of the paths by'
    required: true

outputs:
  directories:
    description: 'The grouped directories in JSON'

runs:
  using: node20
  main: dist/index.js
